# Generated by Django 4.1.3 on 2022-11-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0002_admin_simpleuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='whatdoesyoudo',
            new_name='A_philosophy_statement',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='whoisyou',
            new_name='what_does_you_do',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='who_is_you',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
