# Generated by Django 4.1.3 on 2022-11-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0003_rename_whatdoesyoudo_portfolio_a_philosophy_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='userAccount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApplication.simpleuser'),
        ),
    ]
