# Generated by Django 4.1.3 on 2022-11-20 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0004_account_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolioAccount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApplication.account'),
        ),
    ]
