# Generated by Django 4.1.2 on 2022-11-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0005_portfolio_portfolioaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='His_career_summary',
            new_name='career_summary',
        ),
    ]
