# Generated by Django 4.1.3 on 2022-12-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0006_rename_his_career_summary_portfolio_career_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
